# Generated by Django 2.1.7 on 2019-02-24 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('climate', models.CharField(default='unknown', max_length=255, verbose_name='Climate')),
                ('terrain', models.CharField(default='unknown', max_length=255, verbose_name='Terrain')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
