from django.urls import include, path
from django.views.generic.base import RedirectView

from b2wars.apps.planets.viewsets import PlanetViewSet
from rest_framework import routers
from rest_framework.schemas import get_schema_view
from rest_framework_swagger.renderers import OpenAPIRenderer, SwaggerUIRenderer

router = routers.DefaultRouter()
router.register(r'planets', PlanetViewSet)

schema_view = get_schema_view(
    title='B2Wars API',
    renderer_classes=[OpenAPIRenderer, SwaggerUIRenderer]
)

urlpatterns = [

    # Automatic URL mapping for registered resources
    path('api/', include(router.urls)),
    path('', RedirectView.as_view(url='api/', permanent=False)),

    # Docs generated by swagger
    path('docs/', schema_view, name='docs')
]
